def vault_1983_final():
    print("\n" + "="*50)
    print(" 🏆 1983 CRICKET WORLD CUP FINAL 🏆 ")
    print("="*50)
    print("Date: June 25, 1983")
    print("Venue: Lord's, London")
    print("Result: India won by 43 runs")
    print("-" * 50)
    
    print("🏏 INDIA INNINGS: 183 All Out (54.4 Overs)")
    print("   Top Scorers:")
    print("   - K Srikkanth: 38 (57)")
    print("   - SM Patil: 27 (29)")
    print("   - M Amarnath: 26 (80)")
    print("\n   Key West Indies Bowlers:")
    print("   - A Roberts: 3/32")
    print("   - M Marshall: 2/24")
    print("-" * 50)
    
    print("🏏 WEST INDIES INNINGS: 140 All Out (52 Overs)")
    print("   Top Scorers:")
    print("   - IVA Richards: 33 (28)")
    print("   - PJL Dujon: 25 (73)")
    print("\n   Key India Bowlers:")
    print("   - M Amarnath: 3/12")
    print("   - M Prabhakar: 3/14")
    print("   - Kapil Dev: 1/21 (11 overs)")
    print("="*50)
    print("🌟 Player of the Match: Mohinder Amarnath")
    print("="*50)